### PR TITLE
Use morden.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Is there a reason we still keep --olympic and --frontier flags and modes around?
Well, specifically why we still keep the Olympic option?

**Comment by chriseth** [comment]
People might want to gather some statistics about olympic. I think it does not hurt keeping them. Keep in mind that we want to reach a state where regular users do not use commandline options, everything should be controllable via mist or some other UI.

**Comment by bobsummerwill** [comment]
Fair enough!    Looks like we're missing a --homestead option here, eh :-)
And perhaps still in flu and other places?

**Comment by chriseth** [comment]
Frontier and homestead are the same thing, because we have a fixed transition point. There is something like "homestead test" which is homestead from block 0 on, but that is not something we want to expose here.

**Comment by bobsummerwill** [comment]
Gotcha!

**Pull request merged**
