### PR TITLE
Change the data dir globally and move ipc socket with it.

### PR DESCRIPTION
**Pull request by chriseth**
DEPENDS: {
"libweb3core": "movedatadir"
}

### CODE REVIEW

**Comment by chriseth** [comment]
This seems to break the test environment.

**Comment by bobsummerwill** [comment]
Is "43 tests failed" all of the tests failing?   Looking at http://52.28.164.97/job/project-test/label=master/1540/#showFailuresLink, 

Also, what is the deal with the TTY for the rests with the unreadable characters?

See http://52.28.164.97/job/project-test/label=master/1540/console.

**Comment by chriseth** [comment]
@bobsummerwill I think 43 tests rely on the ipc functionality. the control characters are used to change the text color in logs. We might check whether the terminal supports colours...

**Comment by winsvega** [comment]
Please note that if I run several different ethereum nodes at the same time ipc socket gets overwritten if it is stored globally.

**Comment by chriseth** [comment]
Whisper tests failed on macos, otherwise fine. Will merge.

**Pull request merged**
