### PR TITLE
Correct a mismatch in the web three test modules, where we actually g…

### PR DESCRIPTION
**Pull request by bobsummerwill**
Correct a mismatch in the web three test modules, where we actually get an executable called ethrpctest, where we expect to get one called testweb3.   It looks like there is an ugly mixture of different semantics for how the test folders are used here, such that "ethrpctest" could be built standalone or as part of all the tests.

What we actually get on disk is ethrpctest, so that's what I am going to set the output executable name up as.    This change does not, I believe, modify any of the results of the build process, but it does remove the inconsistency in the build files, which has the nice side-effect of correcting the dependency graph, which is how I spotted this inconsistency in the first place.

Maybe as a follow-up we can consider actually changing the module name in test/CMakeLists.txt, so that you always get "testweb3".  If we do that then we should probably change the ethrpctest into a normal source folder at the same time.

### CODE REVIEW

**Comment by chriseth** [comment]
build fails because of dependencies

**Comment by bobsummerwill** [comment]
Odd.    I saw some issues locally too.    Like this needed a clean build.

Will dig into it next week.

**Comment by chriseth** [comment]
@bobsummerwill please rebase (do not use merge for PRs)

**Comment by bobsummerwill** [comment]
This actually needs more testing as well.    I'll try to get it finished off soon.   Will make an issue for it, so we can track the (small amount of) work.

**Comment by bobsummerwill** [comment]
OK - see https://github.com/ethereum/webthree-umbrella/issues/476.

**Comment by chriseth** [comment]
So the executable that is actually called for testing is testweb3 (the script that calls it is `webthree-helpers/ethtest.sh`). "ethrpctest" seems to be a separate binary which is not a unit test but rather a commandline program that can be used to do some manual testing. We might remove that executable.

Please close this PR to limit work in progress.

**Comment by bobsummerwill** [comment]
See also https://github.com/bobsummerwill/cpp-ethereum/commit/2195910af76d442f572d8ce001a27eef4ef9b481.

**Pull request closed without merging**
